In [1]:
# Import dependencies
import pandas as pd
from sqlalchemy import create_engine

# Sexually Transmitted Disease Table

In [2]:
# Load sexually transmitted disease (STD) data into DataFrame
STD_fp = "Data/Atlas_STD.csv"
STD_df = pd.read_csv(STD_fp, skiprows=6, thousands=',')

In [3]:
# Check initial data types of DataFrame loaded in
STD_df.dtypes

Indicator           object
Year                object
Geography           object
FIPS                 int64
Cases                int64
Rate per 100000    float64
dtype: object

In [4]:
# Remove unneeded columns (i.e., FIPS)
STD_df = STD_df.drop(columns=['FIPS'])

In [5]:
# Remove " (COVID-19 Pandemic)" from 2020 value
STD_df['Year'] = STD_df['Year'].replace('2020 (COVID-19 Pandemic)', 2020)

In [6]:
# Convert Year to an integer
STD_df['Year'] = pd.to_numeric(STD_df['Year'], downcast='integer')

In [7]:
# Check data types
STD_df.dtypes

Indicator           object
Year                 int16
Geography           object
Cases                int64
Rate per 100000    float64
dtype: object

In [8]:
# Keep years before 2017
STD_df = STD_df.loc[STD_df['Year'] < 2017, :]
# Reset index
STD_df = STD_df.reset_index(drop=True)

In [9]:
# Rename columns (Cases: # of STD Cases; Rate per 100000: STD Rate per 100000)
rename_col_dict = {"Cases": "Number_of_STD_Cases", "Rate per 100000": "STD_Rate_per_100000"}
STD_df = STD_df.rename(columns=rename_col_dict)

In [10]:
STD_df.head(25)

,Indicator,Year,Geography,Number_of_STD_Cases,STD_Rate_per_100000
0,Primary and Secondary Syphilis,2016,Alabama,376,7.7
1,Primary and Secondary Syphilis,2015,Alabama,280,5.8
2,Primary and Secondary Syphilis,2014,Alabama,161,3.3
3,Primary and Secondary Syphilis,2013,Alabama,183,3.8
4,Primary and Secondary Syphilis,2012,Alabama,216,4.5
5,Primary and Secondary Syphilis,2011,Alabama,228,4.8
6,Primary and Secondary Syphilis,2010,Alabama,260,5.4
7,Primary and Secondary Syphilis,2009,Alabama,417,8.9
8,Primary and Secondary Syphilis,2008,Alabama,449,9.6
9,Primary and Secondary Syphilis,2007,Alabama,380,8.2
10,Primary and Secondary Syphilis,2006,Alabama,319,6.9
11,Primary and Secondary Syphilis,2005,Alabama,169,3.7
12,Primary and Secondary Syphilis,2004,Alabama,165,3.7
13,Primary and Secondary Syphilis,2003,Alabama,114,2.5
14,Primary and Secondary Syphilis,2002,Alabama,149,3.3
15,Primary and Secondary Syphilis,2001,Alabama,142,3.2
16,Primary and Secondary Syphilis,2000,Alabama,123,2.8
17,Gonorrhea,2016,Alabama,8408,172.9
18,Gonorrhea,2015,Alabama,7196,148.3
19,Gonorrhea,2014,Alabama,7677,158.6
20,Gonorrhea,2013,Alabama,8377,173.4
21,Gonorrhea,2012,Alabama,9270,192.5
22,Gonorrhea,2011,Alabama,9132,190.3
23,Gonorrhea,2010,Alabama,7933,165.8
24,Gonorrhea,2009,Alabama,7498,159.3

# Drug Poisoning Mortality (DPM)

In [11]:
# Load drug poisoning mortality (DPM) data into DataFrame
DPM_fp = "Data/Drug_Poisoning_Mortality_by_State.csv"
DPM_df = pd.read_csv(DPM_fp)

In [12]:
# Check initial data types of DataFrame loaded in
DPM_df.dtypes

State                                            object
Year                                              int64
Sex                                              object
Age Group                                        object
Race and Hispanic Origin                         object
Deaths                                            int64
Population                                        int64
Crude Death Rate                                float64
Standard Error for Crude Rate                   float64
Lower Confidence Limit for Crude Rate           float64
Upper Confidence Limit for Crude Rate           float64
Age-adjusted Rate                               float64
Standard Error for Age-adjusted Rate            float64
Lower Confidence Limit for Age-adjusted Rate    float64
Upper Confidence Limit for Age-adjusted Rate    float64
State Crude Rate in Range                        object
US Crude Rate                                   float64
US Age-adjusted Rate                            float64
Unit                                             object
dtype: object

In [13]:
# Remove unneeded columns
drop_columns=['Sex', 'Age Group', 'Race and Hispanic Origin', 'Unit']
DPM_df = DPM_df.drop(columns=drop_columns)

In [14]:
# Keep years after 1999.
DPM_df = DPM_df.loc[DPM_df['Year'] > 1999, :]

In [15]:
# Keep states only (i.e., remove United States)
DPM_df = DPM_df.loc[DPM_df['State'] != 'United States', :]

In [16]:
# Reset index
DPM_df = DPM_df.reset_index(drop=True)

In [17]:
DPM_df.head(25)

,State,Year,Deaths,Population,Crude Death Rate,Standard Error for Crude Rate,Lower Confidence Limit for Crude Rate,Upper Confidence Limit for Crude Rate,Age-adjusted Rate,Standard Error for Age-adjusted Rate,Lower Confidence Limit for Age-adjusted Rate,Upper Confidence Limit for Age-adjusted Rate,State Crude Rate in Range,US Crude Rate,US Age-adjusted Rate
0,Alabama,2000,197,4447100,4.4299,0.31561,3.8112,5.0485,4.4857,0.31985,3.8588,5.1126,1.8–7.1,6.1882,6.1749
1,Alabama,2001,216,4467634,4.8348,0.32896,4.1900,5.4795,4.8915,0.33329,4.2382,5.5447,1.8–7.1,6.8057,6.7922
2,Alabama,2002,211,4480089,4.7097,0.32423,4.0742,5.3452,4.7619,0.32868,4.1177,5.4062,1.8–7.1,8.1766,8.1957
3,Alabama,2003,197,4503491,4.3744,0.31166,3.7635,4.9852,4.4333,0.31701,3.8120,5.0547,1.8–7.1,8.8881,8.8765
4,Alabama,2004,283,4530729,6.2462,0.37130,5.5185,6.9740,6.3542,0.37944,5.6105,7.0979,1.8–7.1,9.3660,9.3831
5,Alabama,2005,283,4569805,6.1928,0.36813,5.4713,6.9143,6.3330,0.37832,5.5915,7.0745,1.8–7.1,10.0884,10.0699
6,Alabama,2006,398,4628981,8.5980,0.43098,7.7533,9.4427,8.7498,0.44162,7.8842,9.6154,7.1–10.2,11.5373,11.4883
7,Alabama,2007,511,4672840,10.9355,0.48376,9.9874,11.8837,11.0885,0.49516,10.1180,12.0590,10.3–12.6,11.9543,11.8775
8,Alabama,2008,607,4718206,12.8651,0.52218,11.8416,13.8885,12.9811,0.53292,11.9366,14.0256,12.6–16,11.9864,11.8947
9,Alabama,2009,630,4757938,13.2410,0.52754,12.2071,14.2750,13.6077,0.54855,12.5325,14.6828,12.6–16,12.0624,11.9388
10,Alabama,2010,547,4779736,11.4441,0.48932,10.4851,12.4032,11.7688,0.50959,10.7700,12.7676,10.3–12.6,12.4144,12.2966
11,Alabama,2011,552,4802740,11.4934,0.48919,10.5346,12.4523,11.7632,0.50803,10.7674,12.7589,10.3–12.6,13.2674,13.1852
12,Alabama,2012,562,4822023,11.6549,0.49163,10.6913,12.6185,12.0706,0.51722,11.0569,13.0844,10.3–12.6,13.2208,13.1422
13,Alabama,2013,598,4833722,12.3714,0.50590,11.3798,13.3630,12.7176,0.52933,11.6801,13.7551,12.6–16,13.9127,13.8005
14,Alabama,2014,723,4849377,14.9091,0.55448,13.8224,15.9959,15.1532,0.57484,14.0265,16.2799,12.6–16,14.7574,14.6831
15,Alabama,2015,736,4858979,15.1472,0.55833,14.0529,16.2415,15.6639,0.58859,14.5103,16.8176,12.6–16,16.3040,16.2923
16,Alabama,2016,756,4863300,15.5450,0.56537,14.4369,16.6531,16.2075,0.60241,15.0268,17.3883,16–52,19.6925,19.7851
17,Alaska,2000,48,626932,7.6563,1.10510,5.6452,10.1512,7.1077,1.02971,5.2407,9.4238,7.1–10.2,6.1882,6.1749
18,Alaska,2001,62,633714,9.7836,1.24252,7.5010,12.5421,9.3983,1.20475,7.1889,12.0725,7.1–10.2,6.8057,6.7922
19,Alaska,2002,84,642337,13.0772,1.42684,10.4309,16.1905,12.1995,1.33512,9.7168,15.1231,10.3–12.6,8.1766,8.1957
20,Alaska,2003,83,648414,12.8005,1.40503,10.1955,15.8681,12.7245,1.45104,10.0420,15.9034,12.6–16,8.8881,8.8765
21,Alaska,2004,86,659286,13.0444,1.40662,10.4338,16.1097,12.7164,1.39682,10.1286,15.7639,12.6–16,9.3660,9.3831
22,Alaska,2005,79,666946,11.8450,1.33267,9.3778,14.7625,11.3744,1.29691,8.9765,14.2160,10.3–12.6,10.0884,10.0699
23,Alaska,2006,76,675302,11.2542,1.29095,8.8670,14.0863,11.0604,1.29844,8.6696,13.9068,10.3–12.6,11.5373,11.4883
24,Alaska,2007,72,680300,10.5836,1.24729,8.2810,13.3282,10.0941,1.20552,7.8688,12.7533,7.1–10.2,11.9543,11.8775

In [18]:
# Connect to Postgres
protocol = 'postgresql'
username = 'postgres'
password = 'postgres'
host = 'localhost'
port = 5432
database_name = 'sex_drugs_db'
rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database_name}'
engine = create_engine(rds_connection_string)

In [19]:
# Load DataFrames into Postgres